using CommunicationService.Domain.Entities;
using HMSService.Domain.Entities;
using IdentityService.Domain.Entities;
using IdentityService.Domain.Entities.Rbac;
using LISService.Domain.Entities;
using LMSService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using PharmacyService.Domain.Entities;
using SharedService.Domain.Enterprise;
using SharedService.Domain.FeatureExtensions;

namespace TriVita.UnifiedDatabase;

public sealed partial class HealthcareDbContext
{
    // HMS
    public DbSet<HmsVisitType> VisitTypes => Set<HmsVisitType>();
    public DbSet<HmsAppointment> Appointments => Set<HmsAppointment>();
    public DbSet<HmsVisit> Visits => Set<HmsVisit>();
    public DbSet<HmsAppointmentStatusHistory> AppointmentStatusHistories => Set<HmsAppointmentStatusHistory>();
    public DbSet<HmsAppointmentQueue> AppointmentQueues => Set<HmsAppointmentQueue>();
    public DbSet<HmsVital> Vitals => Set<HmsVital>();
    public DbSet<HmsClinicalNote> ClinicalNotes => Set<HmsClinicalNote>();
    public DbSet<HmsDiagnosis> Diagnoses => Set<HmsDiagnosis>();
    public DbSet<HmsMedicalProcedure> MedicalProcedures => Set<HmsMedicalProcedure>();
    public DbSet<HmsPrescription> Prescriptions => Set<HmsPrescription>();
    public DbSet<HmsPrescriptionItem> PrescriptionItems => Set<HmsPrescriptionItem>();
    public DbSet<HmsPrescriptionNote> PrescriptionNotes => Set<HmsPrescriptionNote>();
    public DbSet<HmsPaymentMode> PaymentModes => Set<HmsPaymentMode>();
    public DbSet<HmsBillingHeader> BillingHeaders => Set<HmsBillingHeader>();
    public DbSet<HmsBillingItem> BillingItems => Set<HmsBillingItem>();
    public DbSet<HmsPaymentTransaction> PaymentTransactions => Set<HmsPaymentTransaction>();
    public DbSet<HmsPatientMaster> PatientMasters => Set<HmsPatientMaster>();
    public DbSet<HmsPatientFacilityLink> PatientFacilityLinks => Set<HmsPatientFacilityLink>();
    public DbSet<HmsWard> Wards => Set<HmsWard>();
    public DbSet<HmsBed> Beds => Set<HmsBed>();
    public DbSet<HmsAdmission> Admissions => Set<HmsAdmission>();
    public DbSet<HmsAdmissionTransfer> AdmissionTransfers => Set<HmsAdmissionTransfer>();
    public DbSet<HmsHousekeepingStatus> HousekeepingStatuses => Set<HmsHousekeepingStatus>();
    public DbSet<HmsEmarEntry> EmarEntries => Set<HmsEmarEntry>();
    public DbSet<HmsDoctorOrderAlert> DoctorOrderAlerts => Set<HmsDoctorOrderAlert>();
    public DbSet<HmsOperationTheatre> OperationTheatres => Set<HmsOperationTheatre>();
    public DbSet<HmsSurgerySchedule> SurgerySchedules => Set<HmsSurgerySchedule>();
    public DbSet<HmsAnesthesiaRecord> AnesthesiaRecords => Set<HmsAnesthesiaRecord>();
    public DbSet<HmsPostOpRecord> PostOpRecords => Set<HmsPostOpRecord>();
    public DbSet<HmsOtConsumable> OtConsumables => Set<HmsOtConsumable>();
    public DbSet<HmsPricingRule> PricingRules => Set<HmsPricingRule>();
    public DbSet<HmsPackageDefinition> PackageDefinitions => Set<HmsPackageDefinition>();
    public DbSet<HmsPackageDefinitionLine> PackageDefinitionLines => Set<HmsPackageDefinitionLine>();
    public DbSet<HmsProformaInvoice> ProformaInvoices => Set<HmsProformaInvoice>();
    public DbSet<HmsInsuranceProvider> InsuranceProviders => Set<HmsInsuranceProvider>();
    public DbSet<HmsPreAuthorization> PreAuthorizations => Set<HmsPreAuthorization>();
    public DbSet<HmsClaim> Claims => Set<HmsClaim>();

    // LIS
    public DbSet<LisTestCategory> LisTestCategories => Set<LisTestCategory>();
    public DbSet<LisSampleType> LisSampleTypes => Set<LisSampleType>();
    public DbSet<LisTestMaster> LisTestMasters => Set<LisTestMaster>();
    public DbSet<LisTestParameter> LisTestParameters => Set<LisTestParameter>();
    public DbSet<LisTestReferenceRange> LisTestReferenceRanges => Set<LisTestReferenceRange>();
    public DbSet<LisLabOrder> LisLabOrders => Set<LisLabOrder>();
    public DbSet<LisLabOrderItem> LisLabOrderItems => Set<LisLabOrderItem>();
    public DbSet<LisOrderStatusHistory> LisOrderStatusHistories => Set<LisOrderStatusHistory>();
    public DbSet<LisSampleCollection> LisSampleCollections => Set<LisSampleCollection>();
    public DbSet<LisSampleTracking> LisSampleTrackings => Set<LisSampleTracking>();
    public DbSet<LisLabResult> LisLabResults => Set<LisLabResult>();
    public DbSet<LisResultApproval> LisResultApprovals => Set<LisResultApproval>();
    public DbSet<LisResultHistory> LisResultHistories => Set<LisResultHistory>();
    public DbSet<LisReportHeader> LisReportHeaders => Set<LisReportHeader>();
    public DbSet<LisReportDetail> LisReportDetails => Set<LisReportDetail>();
    public DbSet<LisTestParameterProfile> LisTestParameterProfiles => Set<LisTestParameterProfile>();
    public DbSet<LisAnalyzerResultMap> LisAnalyzerResultMaps => Set<LisAnalyzerResultMap>();
    public DbSet<LisSampleBarcode> LisSampleBarcodes => Set<LisSampleBarcode>();
    public DbSet<LisSampleLifecycleEvent> LisSampleLifecycleEvents => Set<LisSampleLifecycleEvent>();
    public DbSet<LisReportDeliveryOtp> LisReportDeliveryOtps => Set<LisReportDeliveryOtp>();
    public DbSet<LisReportLockState> LisReportLockStates => Set<LisReportLockState>();
    public DbSet<LisAnalyzerResultHeader> LisAnalyzerResultHeaders => Set<LisAnalyzerResultHeader>();
    public DbSet<LisAnalyzerResultLine> LisAnalyzerResultLines => Set<LisAnalyzerResultLine>();

    // LMS
    public DbSet<LmsProcessingStage> LmsProcessingStages => Set<LmsProcessingStage>();
    public DbSet<LmsWorkQueue> LmsWorkQueues => Set<LmsWorkQueue>();
    public DbSet<LmsTechnicianAssignment> LmsTechnicianAssignments => Set<LmsTechnicianAssignment>();
    public DbSet<LmsEquipment> LmsEquipments => Set<LmsEquipment>();
    public DbSet<LmsEquipmentMaintenance> LmsEquipmentMaintenances => Set<LmsEquipmentMaintenance>();
    public DbSet<LmsEquipmentCalibration> LmsEquipmentCalibrations => Set<LmsEquipmentCalibration>();
    public DbSet<LmsQcRecord> LmsQcRecords => Set<LmsQcRecord>();
    public DbSet<LmsQcResult> LmsQcResults => Set<LmsQcResult>();
    public DbSet<LmsLabInventory> LmsLabInventories => Set<LmsLabInventory>();
    public DbSet<LmsLabInventoryTransaction> LmsLabInventoryTransactions => Set<LmsLabInventoryTransaction>();
    public DbSet<IamUserAccount> IamUserAccounts => Set<IamUserAccount>();
    public DbSet<IamRole> IamRoles => Set<IamRole>();
    public DbSet<IamPermission> IamPermissions => Set<IamPermission>();
    public DbSet<IamRolePermission> IamRolePermissions => Set<IamRolePermission>();
    public DbSet<IamUserRoleAssignment> IamUserRoleAssignments => Set<IamUserRoleAssignment>();
    public DbSet<IamUserFacilityScope> IamUserFacilityScopes => Set<IamUserFacilityScope>();
    public DbSet<IamUserMfaFactor> IamUserMfaFactors => Set<IamUserMfaFactor>();
    public DbSet<IamPasswordResetToken> IamPasswordResetTokens => Set<IamPasswordResetToken>();
    public DbSet<IamUserSessionActivity> IamUserSessionActivities => Set<IamUserSessionActivity>();
    public DbSet<LmsTestPackage> LmsTestPackages => Set<LmsTestPackage>();
    public DbSet<LmsTestPackageLine> LmsTestPackageLines => Set<LmsTestPackageLine>();
    public DbSet<LmsTestPrice> LmsTestPrices => Set<LmsTestPrice>();
    public DbSet<LmsLabInvoiceHeader> LmsLabInvoiceHeaders => Set<LmsLabInvoiceHeader>();
    public DbSet<LmsLabInvoiceLine> LmsLabInvoiceLines => Set<LmsLabInvoiceLine>();
    public DbSet<LmsLabPaymentTransaction> LmsLabPaymentTransactions => Set<LmsLabPaymentTransaction>();
    public DbSet<LmsPatientWalletAccount> LmsPatientWalletAccounts => Set<LmsPatientWalletAccount>();
    public DbSet<LmsPatientWalletTransaction> LmsPatientWalletTransactions => Set<LmsPatientWalletTransaction>();
    public DbSet<LmsReferralDoctorProfile> LmsReferralDoctorProfiles => Set<LmsReferralDoctorProfile>();
    public DbSet<LmsReferralFeeRule> LmsReferralFeeRules => Set<LmsReferralFeeRule>();
    public DbSet<LmsReferralFeeLedger> LmsReferralFeeLedgers => Set<LmsReferralFeeLedger>();
    public DbSet<LmsReferralSettlement> LmsReferralSettlements => Set<LmsReferralSettlement>();
    public DbSet<LmsReferralSettlementLine> LmsReferralSettlementLines => Set<LmsReferralSettlementLine>();
    public DbSet<LmsB2BPartner> LmsB2BPartners => Set<LmsB2BPartner>();
    public DbSet<LmsB2BPartnerTestRate> LmsB2BPartnerTestRates => Set<LmsB2BPartnerTestRate>();
    public DbSet<LmsB2BPartnerCreditProfile> LmsB2BPartnerCreditProfiles => Set<LmsB2BPartnerCreditProfile>();
    public DbSet<LmsB2BCreditLedger> LmsB2BCreditLedgers => Set<LmsB2BCreditLedger>();
    public DbSet<LmsB2BPartnerBillingStatement> LmsB2BPartnerBillingStatements => Set<LmsB2BPartnerBillingStatement>();
    public DbSet<LmsB2BPartnerBillingStatementLine> LmsB2BPartnerBillingStatementLines => Set<LmsB2BPartnerBillingStatementLine>();
    public DbSet<LmsReagentMaster> LmsReagentMasters => Set<LmsReagentMaster>();
    public DbSet<LmsReagentBatch> LmsReagentBatches => Set<LmsReagentBatch>();
    public DbSet<LmsTestReagentMap> LmsTestReagentMaps => Set<LmsTestReagentMap>();
    public DbSet<LmsReagentConsumptionLog> LmsReagentConsumptionLogs => Set<LmsReagentConsumptionLog>();
    public DbSet<LmsLabOrderContext> LmsLabOrderContexts => Set<LmsLabOrderContext>();
    public DbSet<LmsReportPaymentGate> LmsReportPaymentGates => Set<LmsReportPaymentGate>();
    public DbSet<LmsFinanceLedgerEntry> LmsFinanceLedgerEntries => Set<LmsFinanceLedgerEntry>();
    public DbSet<LmsAnalyticsDailyFacilityRollup> LmsAnalyticsDailyFacilityRollups => Set<LmsAnalyticsDailyFacilityRollup>();
    public DbSet<SecDataChangeAuditLog> SecDataChangeAuditLogs => Set<SecDataChangeAuditLog>();
    public DbSet<LmsEquipmentType> LmsEquipmentTypes => Set<LmsEquipmentType>();
    public DbSet<LmsEquipmentFacilityMapping> LmsEquipmentFacilityMappings => Set<LmsEquipmentFacilityMapping>();
    public DbSet<LmsCatalogTest> LmsCatalogTests => Set<LmsCatalogTest>();
    public DbSet<LmsCatalogParameter> LmsCatalogParameters => Set<LmsCatalogParameter>();
    public DbSet<LmsCatalogReferenceRange> LmsCatalogReferenceRanges => Set<LmsCatalogReferenceRange>();
    public DbSet<LmsCatalogTestParameterMap> LmsCatalogTestParameterMaps => Set<LmsCatalogTestParameterMap>();
    public DbSet<LmsCatalogPackageParameterMap> LmsCatalogPackageParameterMaps => Set<LmsCatalogPackageParameterMap>();
    public DbSet<LmsEquipmentTestMaster> LmsEquipmentTestMasters => Set<LmsEquipmentTestMaster>();
    public DbSet<LmsCatalogTestEquipmentMap> LmsCatalogTestEquipmentMaps => Set<LmsCatalogTestEquipmentMap>();
    public DbSet<LmsCatalogPackageTestLineMap> LmsCatalogPackageTestLineMaps => Set<LmsCatalogPackageTestLineMap>();
    public DbSet<LmsLabTestBooking> LmsLabTestBookings => Set<LmsLabTestBooking>();
    public DbSet<LmsLabTestBookingItem> LmsLabTestBookingItems => Set<LmsLabTestBookingItem>();
    public DbSet<LmsLabSampleBarcode> LmsLabSampleBarcodes => Set<LmsLabSampleBarcode>();
    public DbSet<LmsCollectionRequest> LmsCollectionRequests => Set<LmsCollectionRequest>();
    public DbSet<LmsRiderTracking> LmsRiderTrackings => Set<LmsRiderTracking>();
    public DbSet<LmsSampleTransport> LmsSampleTransports => Set<LmsSampleTransport>();
    public DbSet<LmsReportValidationStep> LmsReportValidationSteps => Set<LmsReportValidationStep>();
    public DbSet<LmsResultDeltaCheck> LmsResultDeltaChecks => Set<LmsResultDeltaCheck>();
    public DbSet<LmsReportDigitalSign> LmsReportDigitalSigns => Set<LmsReportDigitalSign>();

    // Pharmacy
    public DbSet<PhrMedicineCategory> PhrMedicineCategories => Set<PhrMedicineCategory>();
    public DbSet<PhrManufacturer> PhrManufacturers => Set<PhrManufacturer>();
    public DbSet<PhrComposition> PhrCompositions => Set<PhrComposition>();
    public DbSet<PhrForm> PhrForms => Set<PhrForm>();
    public DbSet<PhrMedicine> PhrMedicines => Set<PhrMedicine>();
    public DbSet<PhrMedicineComposition> PhrMedicineCompositions => Set<PhrMedicineComposition>();
    public DbSet<PhrMedicineBatch> PhrMedicineBatches => Set<PhrMedicineBatch>();
    public DbSet<PhrBatchStock> PhrBatchStocks => Set<PhrBatchStock>();
    public DbSet<PhrStockLedger> PhrStockLedgers => Set<PhrStockLedger>();
    public DbSet<PhrPurchaseOrder> PhrPurchaseOrders => Set<PhrPurchaseOrder>();
    public DbSet<PhrPurchaseOrderItem> PhrPurchaseOrderItems => Set<PhrPurchaseOrderItem>();
    public DbSet<PhrGoodsReceipt> PhrGoodsReceipts => Set<PhrGoodsReceipt>();
    public DbSet<PhrGoodsReceiptItem> PhrGoodsReceiptItems => Set<PhrGoodsReceiptItem>();
    public DbSet<PhrSupplier> PhrSuppliers => Set<PhrSupplier>();
    public DbSet<PhrCustomer> Customers => Set<PhrCustomer>();
    public DbSet<PhrPharmacySale> PhrPharmacySales => Set<PhrPharmacySale>();
    public DbSet<PhrPharmacySalesItem> PhrPharmacySalesItems => Set<PhrPharmacySalesItem>();
    public DbSet<PhrPrescriptionMapping> PhrPrescriptionMappings => Set<PhrPrescriptionMapping>();
    public DbSet<PhrStockAdjustment> PhrStockAdjustments => Set<PhrStockAdjustment>();
    public DbSet<PhrStockAdjustmentItem> PhrStockAdjustmentItems => Set<PhrStockAdjustmentItem>();
    public DbSet<PhrStockTransfer> PhrStockTransfers => Set<PhrStockTransfer>();
    public DbSet<PhrStockTransferItem> PhrStockTransferItems => Set<PhrStockTransferItem>();
    public DbSet<PhrExpiryTracking> PhrExpiryTrackings => Set<PhrExpiryTracking>();
    public DbSet<PhrInventoryLocation> PhrInventoryLocations => Set<PhrInventoryLocation>();
    public DbSet<PhrSalesReturn> PhrSalesReturns => Set<PhrSalesReturn>();
    public DbSet<PhrSalesReturnItem> PhrSalesReturnItems => Set<PhrSalesReturnItem>();
    public DbSet<PhrControlledDrugRegister> PhrControlledDrugRegisters => Set<PhrControlledDrugRegister>();
    public DbSet<PhrBatchStockLocation> PhrBatchStockLocations => Set<PhrBatchStockLocation>();
    public DbSet<PhrReorderPolicy> PhrReorderPolicies => Set<PhrReorderPolicy>();

    // Shared
    public DbSet<Address> Addresses => Set<Address>();
    public DbSet<ContactDetails> ContactDetails => Set<ContactDetails>();
    public DbSet<EnterpriseRoot> Enterprises => Set<EnterpriseRoot>();
    public DbSet<Company> Companies => Set<Company>();
    public DbSet<BusinessUnit> BusinessUnits => Set<BusinessUnit>();
    public DbSet<Facility> Facilities => Set<Facility>();
    public DbSet<Department> Departments => Set<Department>();
    public DbSet<EnterpriseB2BContract> EnterpriseB2BContracts => Set<EnterpriseB2BContract>();
    public DbSet<FacilityServicePriceList> FacilityServicePriceLists => Set<FacilityServicePriceList>();
    public DbSet<FacilityServicePriceListLine> FacilityServicePriceListLines => Set<FacilityServicePriceListLine>();
    public DbSet<CrossFacilityReportAudit> CrossFacilityReportAudits => Set<CrossFacilityReportAudit>();
    public DbSet<ModuleIntegrationHandoff> ModuleIntegrationHandoffs => Set<ModuleIntegrationHandoff>();
    public DbSet<TenantOnboardingStage> TenantOnboardingStages => Set<TenantOnboardingStage>();
    public DbSet<LabCriticalValueEscalation> LabCriticalValueEscalations => Set<LabCriticalValueEscalation>();

    // Identity
    public DbSet<AppUser> Users => Set<AppUser>();
    public DbSet<IdentityRole> IdentityRoles => Set<IdentityRole>();
    public DbSet<IdentityPermission> IdentityPermissions => Set<IdentityPermission>();
    public DbSet<IdentityUserRole> IdentityUserRoles => Set<IdentityUserRole>();
    public DbSet<IdentityRolePermission> IdentityRolePermissions => Set<IdentityRolePermission>();
    public DbSet<IdentityUserFacilityGrant> IdentityUserFacilityGrants => Set<IdentityUserFacilityGrant>();
    public DbSet<IdentityRefreshToken> IdentityRefreshTokens => Set<IdentityRefreshToken>();
    public DbSet<IdentityAccountLockoutState> IdentityAccountLockoutStates => Set<IdentityAccountLockoutState>();
    public DbSet<IdentityLoginAttempt> IdentityLoginAttempts => Set<IdentityLoginAttempt>();
    public DbSet<IdentityPasswordResetToken> IdentityPasswordResetTokens => Set<IdentityPasswordResetToken>();
    public DbSet<IdentityUserProfile> IdentityUserProfiles => Set<IdentityUserProfile>();

    // Communication
    public DbSet<ComNotification> Notifications => Set<ComNotification>();
    public DbSet<ComNotificationRecipient> NotificationRecipients => Set<ComNotificationRecipient>();
    public DbSet<ComNotificationChannel> NotificationChannels => Set<ComNotificationChannel>();
    public DbSet<ComNotificationTemplate> NotificationTemplates => Set<ComNotificationTemplate>();
    public DbSet<ComNotificationLog> NotificationLogs => Set<ComNotificationLog>();
    public DbSet<ComNotificationQueue> NotificationQueues => Set<ComNotificationQueue>();
}
